name: UnderTheGun
favicon: null
layout_spectrum: 0.95633
typography_spectrum: 0.20218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ac4ac'
    - '#171717'
    - '#503f38'
    - '#917466'
  brandStrength: 0.6875
  lightness: 0.8166743947658688
  saturation: 0.1875
  rhythmicContrast: 0.3976354245096445
purpose: []
