name: UnderTheGun
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20218
title: UnderTheGun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfb'
    - '#131311'
    - '#654e40'
    - '#8a2d1b'
    - '#a59484'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
