name: UnderTheGun
favicon: null
layout_spectrum: 0.07859
typography_spectrum: 0.20218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4504ff'
    - '#8a8888'
    - '#000000'
    - '#7d6f9e'
    - '#3803cf'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
