name: UnderTheGun
favicon: null
layout_spectrum: 0.93857
typography_spectrum: 0.20218
title: UnderTheGun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ac4ac'
    - '#171717'
    - '#503f38'
    - '#917466'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
